baseURL = "/"
languageCode = "en-us"
title = "Online CSE Courses @ IIT Madras"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    # show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/cse-iitm.svg"
    mobile_height = "36px"
    desktop = "images/logo/cse-iitm.svg"
    desktop_height = "80px"
    alt = "CSE Dept, IIT Madras"

  [params.footer]
    copyright_text = 'Theme design by <a class="zerostatic" href="https://www.zerostatic.io">zerostatic</a> <br>Made with <b>love</b> by <a href="https://www.rudradesai.in/">Rudra Desai</a>'

[menu]
  # Main Menu
  # [[menu.main]]
  #   name = "Courses"
  #   url = "/courses/"
  #     weight = 1

  # [[menu.main]]
  #     name = "Team"
  #     url = "/team/"
  #     weight = 2

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

  # [[menu.main]]
  #     name = "Contact"
  #     url = "/contact/"
  #     weight = 4

  # Footer Menu
  # [[menu.footer]]
  #   name = "Home"
  #   url = "/"
  #     weight = 1

  # [[menu.footer]]
  #   name = "Contact"
  #   url = "/contact/"
  #     weight = 2
